### ISSUE TITLE
unrecognized token error

### ISSUE THREAD

**Issue by Ph0non** [quinnj/SQLite.jl#62]
It seems that the SQLite package have problems with creating tables where colnames are identical to hex-values.

```
create(db, "clearance", q[2:end, :], ["nuclide", "OF", "1a", "2a", "3a"])
Error: SQLite.SQLiteException("unrecognized token: \"1A\"")
```
Alternative names are possible, but is it also possible to fix it? The colnames are given by law in my case, so I really don't want to change them.

**Comment by Sean1708** [comment]
I think this is actually a constraint made by SQLite itself since I get the same error from the SQLite REPL.

```sql
SQLite version 3.8.7.4 2014-12-09 01:34:36
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
>>> CREATE TABLE clearance (1a TEXT);
Error: unrecognized token: "1a"
>>> CREATE TABLE clearance (1a TEXT, 2b INT);
Error: unrecognized token: "1a"
```

Currently you can solve this by quoting the three columns like so

```julia
julia> using SQLite

julia> db = SQLiteDB()
SQLite.SQLiteDB{UTF8String}("",Ptr{Void} @0x00007f81bbf37200,0)

julia> q = [1   2   3   4   5
            10  20  30  40  50
            100 200 300 400 500]
3x5 Array{Int64,2}:
   1    2    3    4    5
  10   20   30   40   50
 100  200  300  400  500

julia> create(db, "clearance", q[2:end, :], ["nuclide", "OF", "\"1a\"", "\"2a\"", "\"3a\""])
1x1 SQLite.ResultSet
| Row | "Rows Affected" |
|-----|-----------------|
| 1   | 0               |

julia> query(db, """SELECT "1a" FROM clearance""")
2x1 SQLite.ResultSet
| Row | "1a" |
|-----|------|
| 1   | 30   |
| 2   | 300  |
```

@quinnj Can you think of any downsides to automatically quoting column names in `create`?

**Comment by Ph0non** [comment]
Thanks for the fast help. I didn't thought about a possible constrain in sqlite itself.

**Comment by Sean1708** [comment]
That's ok. I'm gonna leave this open for the time being until Jacob can weigh in on whether automatically quoting column names is a good idea or not.

**Comment by quinnj** [comment]
I'm not quite sure how we'd do the quoting, unless we had a really smart SQL parser of some sort to figure out column names. Am I missing something simpler there?

**Comment by Sean1708** [comment]
Sorry, I meant specifically in `create`.

**Comment by Sean1708** [comment]
I'm gonna close this since it's probably not worth implementing anyway.
