### ISSUE TITLE
can we add transposition for Resultset ?

### ISSUE THREAD

**Issue by songroom** [quinnj/SQLite.jl#63]
we can get a ResultSet data type
```
rsData  = query(db,strSQL)
```
but if we can transpose rsData as matrix , it may looks like:
~~~
A =["a" 1 2 ; "b" 2  4]
B=A'
,....
rsData =rsData'
~~~
we can loop it at col not  row to get array or dict{}, the speed would increase .

**Comment by quinnj** [comment]
You can currently do `Matrix(rsData)` to convert a `ResultSet` to a matrix, then you have all the functionality of matrices. I think we're going to keep ResultSets purposely limited in functionality for viewing query results, but if you need to do anything with them, it's best to convert to a Matrix or DataFrame.

**Comment by songroom** [comment]
thank you!
