### ISSUE TITLE
Inconsistent insert behaviour

### ISSUE THREAD

**Issue by 2nNguyen** [quinnj/SQLite.jl#74]
I'm not sure if it is by design or not but table inserts by dictionary is different to array data. e.g.
```
query(db, "insert into T values (:a,:b)", Dict(:a=>true, :b=>1) )
query(db, "insert into T values (?,?)", [true, 2] )

query(db, "select * from T")
2x2 SQLite.ResultSet
| Row | "col1" | "col2" |
|-----|--------|--------|
| 1   | true   | 1      |
| 2   | 1      | 2      |
```
In the the first instance the boolean values was serialized, while in the second case it was converted to an integer.
Is there a way to obtain the second behaviour using data in the form of a dictionary?

**Comment by quinnj** [comment]
This is actually Julia behavior, not SQLite-specific:
```julia
julia> [true, 2]
2-element Array{Int64,1}:
 1
 2
```
I believe it's because we have:
```julia
julia> subtypes(Integer)
4-element Array{Any,1}:
 BigInt
 Bool
 Signed
 Unsigned
```
I.e. `Bool` is a subtype of `Integer`, so there's some automatic conversion that's going on.

**Comment by Sean1708** [comment]
@2nNguyen you can emulate the behaviour by defining your own `bind` method for `Bool`, see [this](https://github.com/quinnj/SQLite.jl/blob/tutorials/doc/SQLite.ipynb) notebook for more (slightly out of date) information.

The short version is that you can put

```julia
Base.bind(stmt::SQLiteStmt, i::Int, val::Bool) = bind(stmt, i, int(val))
```

before your first `query` and the behaviour will be what you want.

**Comment by quinnj** [comment]
You could also just make sure the automatic conversion doesn't happen:
```julia
julia> Any[true, 2]
2-element Array{Any,1}:
 true
    2

julia>
```

**Comment by 2nNguyen** [comment]
thanks @Sean1708 ,
 ` Base.bind(stmt::SQLiteStmt, i::Int, val::Bool) = bind(stmt, i, int(val))`
 did the trick. I initially tried the example in the main readme in the master branch:
 `sqlreturn(context, val::Bool) = sqlreturn(context, int(val))` 
but that didn't seem to do anything.

**Comment by Sean1708** [comment]
That's understandable, they are very similar but used for different things. 

`sqlreturn` is used when you define your own [scalar](https://www.sqlite.org/lang_corefunc.html) or [aggregate](https://www.sqlite.org/lang_aggfunc.html) functions which are run inside the database.

`bind` is used for [parameter binding](https://www.sqlite.org/c3ref/bind_blob.html) which is what you are doing.

I think I really need to work on some better documentation for this stuff.
